/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.tests;

import org.example.Config;
import org.example.robots.InfoAlertModalRobot;
import org.example.robots.LoginScreenRobot;
import org.example.robots.UserScreenRobot;
import org.example.screens.LoginScreen;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class AppTest extends BaseTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(AppTest.class.getName());

    @Test
    public void checkTextBtn1Test() {
        LOGGER.info("checkTextBtn1 test start");
        final String EXPECTED_TEXT = "Войти";
        LoginScreen loginScreen = new LoginScreen();
        new LoginScreenRobot(loginScreen).assertLoginBtnText(EXPECTED_TEXT);
        LOGGER.info("checkTextBtn1 end");
    }

    @Test
    public void failTest() {
        LOGGER.info("fail test start");
        final String EXPECTED_TEXT = "something wrong";
        LoginScreen loginScreen = new LoginScreen();
        new LoginScreenRobot(loginScreen).checkLoginBtnText(EXPECTED_TEXT);
        LOGGER.info("failTest end");
    }

    @Test
    public void loginTest() {
        LOGGER.info("loginTest test start");
        final String EXPECTED_TEXT = "Успешная авторизация!";
        LoginScreen loginScreen = new LoginScreen();
        new LoginScreenRobot(loginScreen)
                .assertVisibleElements()
                .typeUserName(Config.getUserLogin())
                .typePassword(Config.getUserPass())
                .clickToLoginBtn();

        new InfoAlertModalRobot()
                .assertVisibleElements()
                .checkMsgText(EXPECTED_TEXT)
                .clickOkBtn()
                .checkDisappear();
        new UserScreenRobot()
                .assertVisibleElements();
        LOGGER.info("loginTest end");
    }

}
