plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.myapplication'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"
        testInstrumentationRunnerArgument "allure.results.directory", "/sdcard/Download/allure-results"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packaging {
            resources.excludes.add("META-INF/INDEX.LIST")
    }
    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }

}

dependencies {
    implementation libs.junit.foundation
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit4
    testImplementation libs.allure.junit4
    androidTestImplementation libs.junit4
    androidTestImplementation libs.allure.junit4
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.uiautomator

    androidTestImplementation(libs.allure.kotlin.junit4)
    androidTestImplementation(libs.allure.kotlin.model)
    androidTestImplementation(libs.allure.kotlin.commons)
    androidTestImplementation(libs.allure.kotlin.android)
    //androidTestImplementation libs.junit.foundation
    androidTestUtil("androidx.test:orchestrator:1.5.1")

}
def deviceAllureResultsDir = "/sdcard/googletest/test_outputfiles/."
def localAllureResultsDir = project.layout.buildDirectory.dir("reports").get().asFile


tasks.register("cleanPulledAllureResults", Delete) {
    delete(localAllureResultsDir)
}

tasks.register("pullAllureResults", Exec) {
    dependsOn("cleanPulledAllureResults")
    inputs.property("deviceAllureResultsDir", deviceAllureResultsDir)
    outputs.dir(localAllureResultsDir)
    doFirst {
        localAllureResultsDir.mkdirs()
    }
    commandLine "adb", "pull", deviceAllureResultsDir, localAllureResultsDir.absolutePath
}