/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.codeborne.selenide.Selenide;

import org.example.pages.LoginPage;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class AppTest extends BaseTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(AppTest.class.getName());

    @Test
    public void checkTextBtn1Test() {
        LOGGER.info("checkTextBtn1 test start");
        final String EXPECTED_TEXT = "Войти";
        LoginPage loginPage = Selenide.page(LoginPage.class);
        assertEquals(
                EXPECTED_TEXT,
                loginPage.getLoginBtnText(),
                "У кнопки Войти неправильный текст"
        );
    }

    @Test
    public void loginTest() {
        LOGGER.info("loginTest test start");
        LoginPage loginPage = Selenide.page(LoginPage.class);
        loginPage.typeUserName("user@pflb.ru");
        loginPage.typePassword("user");
        loginPage.clickToLoginBtn();
    }

}
