/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.codeborne.selenide.Selenide;

import org.example.screens.InfoAlert;
import org.example.screens.LoginScreen;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class AppTest extends BaseTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(AppTest.class.getName());

    @Test
    public void checkTextBtn1Test() {
        LOGGER.info("checkTextBtn1 test start");
        final String EXPECTED_TEXT = "Войти";
        LoginScreen loginScreen = Selenide.page(LoginScreen.class);
        assertEquals(
                EXPECTED_TEXT,
                loginScreen.getLoginBtnText(),
                "У кнопки Войти неправильный текст"
        );
    }

    @Test
    public void loginTest() {
        LOGGER.info("loginTest test start");
        Selenide.page(LoginScreen.class)
                .typeUserName(Config.getUserLogin())
                .typePassword(Config.getUserPass())
                .clickToLoginBtn();
        InfoAlert infoAlert = Selenide.page(InfoAlert.class);
        assertEquals("Успешная авторизация!", infoAlert.getMsgText());
        infoAlert.clickOkBtn();
        infoAlert.checkDisappear();
    }

}
